### ISSUE TITLE
Clean up tests/data directory to reduce size

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#1005]
The `tests/data` directory could be significantly smaller in size with a little housekeeping. For example, the `tests/data/import` directory is 94 MB and includes an uncompressed tar file _and_ the contents of the tar file.

**Comment by emthompson-usgs** [comment]
Good point. It is a mess, and I think there is event some data in there that we don't use anymore as we've updated unit tests.

**Comment by emthompson-usgs** [comment]
Note: we have never tracked the mapping between specific unit tests and the data that they use. We should add a README in `tests/data` to track this mapping so that when a unit test is removed we can easily tell if we should remove the data it is using. Similarly, we can modify unit tests to reuse more of the data in many cases.
