### ISSUE TITLE
'Failed' vs. 'Failure' parameter

### ISSUE THREAD

**Issue by jrekoske-usgs** [usgs/groundmotion-processing#158]
Some processing checks set a parameter called 'failure' while others set a parameter called 'failed'. This should be fixed to be consistent.

**Comment by emthompson-usgs** [comment]
The key thing is to be consistent with the `check_stream` method:
https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/stationstream.py#L145
So all should use 
```
            tr.setParameter('failure', {
                'module': __file__,
                'reason': <text describing failure>
            })
```
This is a good example of why duplicate code is bad. Can you make a generic method that does this to ensure consistency? I guess it would have to take in the value for 'module' as an argument since `__file__` would return the location of the new method rather than the module where the failure occurred otherwise.

**Comment by emthompson-usgs** [comment]
It appears that GitHub Projects doesn't close an issue when we mark it as "done" as Waffle did... so I'm closing this now.
