### ISSUE TITLE
Use ReportLab rather than LaTeX to generate reports?

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#181]
Generating PDF reports from Python may be cleaner using ReportLab (direct building of the PDF using Python) rather than Python -> LaTeX -> PDF.

The disadvantage of ReportLab is that figures must be images and cannot be PDF files, although I think there may be  workarounds.

**Comment by emthompson-usgs** [comment]
Currently, we are making the summary plots as png files anyway, and embedding them in the pdfs. We thought this made sense because there's so many data points in the figures that the png files are probably much more efficient in terms of file size. I was not previously aware of ReportLab, but I would think that we can support both. Some other factors to consider:
- One problem is that latex is a huge and complex dependency. We were thinking we would just leave it to users to install as needed. 
- But latex table representations are relatively easy to get for the provenance steps. This might not be a big deal because it looks like tables might not be too difficult in ReportLab. 
- Latex has been around forever and is pretty stable. I'm unsure of ReportLab's longevity and status as freely available. I could be totally off base, but quickly looking at their website makes it seem very corporate, and it is clear that they sell "premium" version so ReportLab, which I think would be a less desirable dependency.

**Comment by baagaard-usgs** [comment]
I think it would be pretty easy to implement a ReportLab version of reports matching what you produce via LaTeX. I can take this on, but I might not get to it before the v1.0 release.

**Comment by baagaard-usgs** [comment]
I am going to close this issue. In working with "projects" with hundreds of earthquakes, PDF files on a per event basis are difficult use.

See #1019 for an idea of a more advanced review tool.
