### ISSUE TITLE
Break up gmprocess --process step into three steps (waveforms, waveform metrics, station metrics)

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#318]
Do we want to break up the the `gmprocess` `--process` step into `--process-waveforms`, `--compute-station-metrics`, and `--compute-waveform-metrics`? I can see how many users want to tune the waveform processing, and then once that is dialed in, compute the metrics. Likewise, it would be nice to be able to recompute the station metrics if the event location changes without reprocessing the waveforms or recomputing the waveform metrics.

Alternatively, breaking this step into multiple steps could be left for users writing Python scripts rather than the `gmprocess`.

**Comment by emthompson-usgs** [comment]
I support this. Is this something you have time to do? I can't right now. The only argument against this is that it might be more difficult than it should be. 

It has been a while since I looked at the code in detail, but I think that separating out the process waveforms and waveform metrics steps should be pretty easy. I can't recall exactly where the station metrics are calculated, but I think that it may be buried somewhere and so it could be less easy to separate out.

**Comment by baagaard-usgs** [comment]
I will look to see how simple/complicated this is. If it looks straightforward, I will do it.

Do we have any tests setup for gmprocess?

**Comment by emthompson-usgs** [comment]
Okay, sounds good. The gmprocess test is here:
https://github.com/usgs/groundmotion-processing/blob/master/tests/bin/gmprocess_test.py

**Comment by mhearne-usgs** [comment]
Brad - The only caveat is making sure that things downstream of the different metrics can handle instances where station or stream metrics are NOT present. Currently the export command assumes that both types of metrics have been calculated.

**Comment by emthompson-usgs** [comment]
This is superseded by #541.
