### ISSUE TITLE
No module named 'gmprocess.io.fdsn.core'

### ISSUE THREAD

**Issue by arkottke** [usgs/groundmotion-processing#606]
**Describe the bug**

Trying to run `gmrecords assemble` but not records are added to the workspace. The issue appears to be that the files are trying to be read by `gmprocess.io.fdsn.core`, but this module has been refactored. Exception of `No module named 'gmprocess.io.fdsn.core'` is being reported from [here](https://github.com/usgs/groundmotion-processing/blob/e272bda17f58fdb3f6f9421b40a9ab7ef6df19f3/gmprocess/io/read_directory.py#L57).

**Comment by emthompson-usgs** [comment]
I think this is a github issue that I don't understand. I renamed the `fdsn` package to `obspy` since it is meant to support any readers obspy supports. But those sub-packages are auto imported, and for some reason the `fdsn` directory sticks around after rebasing. The fix should be just to manually delete the `gmprocess/io/fdsn` directory. I wish I understood why this happened so I could avoid it in the future.

**Comment by arkottke** [comment]
That makes sense. Thanks Eric.
