### ISSUE TITLE
Error when station does not have any horizontal channels.

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#625]
the compute_waveform_metrics portion of `gmrecords` errors out when certain stations do not have a horizontal channel present. I assume that the solution is to ignore these stations and then move onto the next.

To reproduce:
After downloading, assembling, and processing the data for event `us70005p8j`, run
```gmrecords compute_waveform_metrics -e us70005p8j```

The result is `gmprocess.metrics.exception.PGMException: MetricsController: At least one horizontal channel is required for calculations of SA, ROTD, GMROTD, GM `

The error is at [this point in the code.](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/metrics/metrics_controller.py#L550)

**Comment by emthompson-usgs** [comment]
I wouldn't really classify this as a bug because this case the exception is appropriate. This is actually oddly serendipitous because earlier today @arkottke added a new processing step called `check_instrument` [here](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/waveform_processing/processing.py#L552). You should add this step to your processing set `require_two_horiz=True` and this will prevent the error.
