### ISSUE TITLE
Tool for integrating Jupyter notebooks into documentation built with Sphinx

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#680]
It is possible to integrate Jupyter notebooks (e.g., cookbooks, examples) into documentation built with Sphinx. It requires the documentation and notebooks be constructed using a certain set of tools. The advantage of this approach is that you only need to maintain a single source (notebooks) for cookbooks and examples; the code and the discussion of it don't become separated as is the case if you have the information separated into config files, scripts, and a manual.

[MyST - Markedly Structured Text](https://myst-parser.readthedocs.io/en/latest/): MyST allows you to write Sphinx documentation entirely in markdown. MyST markdown provides a markdown equivalent of the reStructuredText syntax, meaning that you can do anything in MyST that you can do with reStructuredText. It is an attempt to have the best of both worlds: the flexibility and extensibility of Sphinx with the simplicity and readability of Markdown.

[MyST{NB}](https://myst-nb.readthedocs.io/en/latest/index.html): Read, write, and execute Jupyter Notebooks in Sphinx

**Comment by emthompson-usgs** [comment]
I converted [one tutorial](https://usgs.github.io/groundmotion-processing/contents/tutorials/response_spectra.html) to myst-nb and I think it looks really good and meets the need for auto-generating/testing the content of the docs rather than having to manually populate it as we had to do before. So, although there are some downsides to this, I think the benefits outweigh them.
