### ISSUE TITLE
Compatibility of event json file with ComCat geojson

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#717]
@emthompson-usgs @mhearne-usgs 

The `event.json` file that is required in the data directory for each event looks to have a custom layout rather than matching the geojson layout of ComCat geojson files. I am confused as to why we aren't just using geojson files consistent with those produced by ComCat. If we are getting the event information from ComCat the vast majority of the time, why create a separate file rather than just downloading the geojson file and using that?

I propose that we either switch the format of `event.json` to be geojson and consistent with the geojson from ComCat *or* we add the option of reading `event.geojson` (geosjon from ComCat) instead of `event.json`.

**Comment by emthompson-usgs** [comment]
I'm unclear what ComCat geojson files you are referring to. I think origins/moment tensors are given as quakeml in Comcat. I think we did the custom event.json format in gmprocess because it seemed like quakeml was massively over complicated. That said, I think that we've run into some problems using our simpler format because we take the "authoritative" origin, and sometimes that is not the magnitude type we'd prefer (e.g., moment magnitude is available but it isn't authoritative). 

I'll look into using quakeml but also please give me an example of the comcat event.geojson.

**Comment by baagaard-usgs** [comment]
[ComCat API documentation](https://earthquake.usgs.gov/fdsnws/event/1/)
Example: https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&eventid=us7000fes8

Here is the subset of geojson we care about:
```json
{
"properties": {
    "time":1632723442319,
    "mag": 6,
    "magType": "mww"
},
"geometry": {
"type": "Point",
"coordinates": [25.2595, 35.2523, 8.71]
},
"id": "us7000fes8"
}
```

Mapping from geojson to json:
```python
origintime = datetime.datetime.fromtimestamp(event["properties"]["time"]/1000.0)
evdict = {
    "id": event["id"],
    "time": origintime.strftime("%Y-%m-%dT%H:%M:%S.%f"),
    "lat": event["geometry"]["coordinates"][1],
    "lon": event["geometry"]["coordinates"][0],
    "depth": event["geometry"]["coordinates"][2],
    "magnitude": event["properties"]["mag"],
    "magnitude_type": event["properties"]["magType"],
}
```
