### ISSUE TITLE
Add unit test for computing station metrics for an event with a finite rupture

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#796]
The idea is for the unit tests to hit this section of code:
https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/subcommands/compute_station_metrics.py#L154

**Comment by gferragu** [comment]
To test the code here a non-point-source rupture needs to be used. Two events are passed to [_test_compute_station_metrics.py,](https://github.com/usgs/groundmotion-processing/blob/1bd224965b645a45c09ac5fafad3fd141b0cbda7/tests/gmprocess/subcommands/compute_station_metrics_test.py#L21) one of which appears to be a rupture with geometry. The data for this event (ci38457511) appears in different locations in [gmprocess/data/testdata](https://github.com/usgs/groundmotion-processing/tree/1bd224965b645a45c09ac5fafad3fd141b0cbda7/gmprocess/data/testdata) though and some do not include rupture information. The unit test is pulling from [/testdata/demo_steps/compute_metrics](https://github.com/usgs/groundmotion-processing/tree/7875b26c16ca236245b60420c1cbc78f238c724a/gmprocess/data/testdata/demo_steps/compute_metrics/ci38457511), where there is only an event.json, a workspace file, and raw data. A[ testdata/fdsn/](https://github.com/usgs/groundmotion-processing/tree/1bd224965b645a45c09ac5fafad3fd141b0cbda7/gmprocess/data/testdata/fdsn) directory  has the same event, but also contains a [rupture.json](https://github.com/usgs/groundmotion-processing/blob/1bd224965b645a45c09ac5fafad3fd141b0cbda7/gmprocess/data/testdata/fdsn/ci38457511/rupture.json), a [station xml file](https://github.com/usgs/groundmotion-processing/blob/1bd224965b645a45c09ac5fafad3fd141b0cbda7/gmprocess/data/testdata/fdsn/ci38457511/CI.CLC.xml), and a [.grd file](https://github.com/usgs/groundmotion-processing/blob/1bd224965b645a45c09ac5fafad3fd141b0cbda7/gmprocess/data/testdata/fdsn/ci38457511/test_grid.grd)

Can a rupture.json file just be copied over to the /demo_steps/ directory for this event? I'm not very familiar with how rupture objects are read in here, but I assume the data directory is checked for geometry information when read in. It would just need to fail `if isinstance(rupture, rupt.point_rupture.PointRupture):` [here](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/subcommands/compute_station_metrics.py#L141) in order to cover that untested section

**Comment by emthompson-usgs** [comment]
I would avoid moving test data around on the fly if possible because that can get confusing. The current unit test is getting data for each event from `gmprocess/data/testdata` and there's no `rupture.json` file for either one (it would be in the event id subdirectory). I think the simple way to do this would be to create a copy the ci38457511 event directory and name it something like "ci38457511_rupt" and then add the `rupture.json` file to it. Then, copy the `test_compute_station_metrics` function and call it something like `test_compute_station_metrics_rupt` and then change it to point to this new event directory. There'd be no reason to repeat the other event (ci38038071) here, so modify the test so that it doesn't run that event.
