### ISSUE TITLE
adding Vs30 values

### ISSUE THREAD

**Issue by hadigh** [usgs/groundmotion-processing#807]
**Is your feature request related to a problem? Please describe.**
My understanding is that Vs30 values for each station can be stored in StationMetricsXML, if so,

- can I please have an example of such xml file?  
- also is it possible to indicate if it is a measured or proxy value?
- is there a way to define a "custom" Vs30 tag in obspy stationxml that can then be read by the "assemble" command?

I noticed that there is a way to point to the Vs30 grid file from config and then compute Vs30 at the station, but this is not going to work for me as I have individual measurements at the location of stations, and would be easier to directly write them to xml file. 

Thanks!

**Comment by emthompson-usgs** [comment]
We don't currently have a mechanism for specifying station-specific Vs30 values. For other reasons, we were going to look into how we are handling stationxml metadata so we can also look into getting Vs30. In the mean time, you may just want to append Vs30 to the output tables since I don't think there's much use for Vs30 until then.

**Comment by hadigh** [comment]
Yes, sounds like a sensible temp solution. Thanks
