### ISSUE TITLE
Vertical component will not be processed if one of the horizontal ones fail

### ISSUE THREAD

**Issue by hadigh** [usgs/groundmotion-processing#826]
**Describe the bug**
the Stream with an acceptable vertical component is labeled as "Failed" due to the failure of one of the horizontal components; this prevents the "passed" vertical trace to be processed by the code!  

**To Reproduce**
I have attached the input file to this message. in this case, BHE, and BHZ traces are passed but the stream is labeled as "failed" due to the failure of the BHN channel. (the results can be produced using a general config file generated by the program)

**Expected behavior**
the vertical trace to be passed and processed 

[20000925155013.zip](https://github.com/usgs/groundmotion-processing/files/7749616/20000925155013.zip)

**Comment by mliau** [comment]
**Describe the bug**
In contrast with what hadigh requested, I would like to keep the two horizontal components of a stream when only the vertical component is rejected.

**To reproduce**
I used the default configuration file where "use_streamcollection" is set to true.

**Expected behavior**
The two horizontal components of a stream are still processed if only the vertical component fails.

**Comment by emthompson-usgs** [comment]
@gferragu Can you please take this? This will require a config option to control the behavior and we don't want to change the current default behavior at this time. The `check_stream` method will need to be passed the config object. Also, please use the example files provided by @hadigh to make new unit test to verify the new functionality.

**Comment by emthompson-usgs** [comment]
@gferragu I got another urgent request for this today so I think I'll take care of this.
