### ISSUE TITLE
Support config updates

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#855]
A persistent issue is that users get errors because the config becomes outdated as we add new functionality. The only way to fix it is to manually edit it or start a new project and neither of these are great options. When we validate, rather than raise an exception it would be better if we detected the missing/incorrect keys and prompt the user to add/replace it, giving them the option to accept the default value (if one exists).

**Comment by baagaard-usgs** [comment]
@emthompson-usgs There seems to be a lot of recent changes affecting the config files. Is it worth revisiting the decision to include all parameters in the config file rather than having a default config file and requiring the user to only list values that override default values? As long as a user can easily see what the default values are and they are included in the provenance information, default values might be easier on end users compared to having to maintain config files that list all values.

**Comment by emthompson-usgs** [comment]
A barrier to this is that in some cases we have optional config keys and we use the presence of those keys to mean that something should be done. An example of this is the individual fetchers; they are turned off by deleting them. I don't think that it is possible to distinguish between when a key is missing due to a previous choice by the user (in which case the default values should not be used) and when a key is missing because the config structure has been changed (in which case the default values should be used). 

One solution would be to make all sections required, and add a boolean key like `enabled: True` to get around inferring that a process should not be performed from the key not being present.

**Comment by NNovoa-CDWR** [comment]
I would definitely support a separate config file. Maybe not a call it a default, but an example minimum base configs. You can just add some comments saying see the master config file for additional options, fetchers, etc. The current config file is very long. I think I tried to count one time and there are over 100 different possible configuration settings in the current file. It is definitely intimidating to new users. I think having a minimum base config will help encourage use of gmprocess.

**Comment by emthompson-usgs** [comment]
@NNovoa-CDWR thanks for weighing in, and I agree that the config has become unwieldy. We can also break it up into multiple smaller configs. Right now, we have:
```
conf/
└── config.yml
```
and that conf has something on the order of 700 lines, many of which the user doesn't care about. We break it up like this:
```
conf/
├── user.yml
├── fetchers.yml
├── windows.yml
...
└── processing.yml
```
And in this case, the only required file would be `user.yml` and the rest are all optional and would overwrite default values. 

This would be a pretty major change but is probably warranted and should make things smoother going forward. 

@baagaard-usgs Does this make sense to you? One thing I am unsure of is how to handle the default values. We can have the `get_config` method start with the defaults that are distributed with the code and then merge in any of these project config files. Or we could have a copy of it placed in the conf file as a reference for users to easily be able to see all of the possible options. If this is used as the source of the defaults then it opens up the possibility for users to mess it up accidentally and it would also require a new mechanism to update it when the code is updated. So I kind of don't like this option. Maybe we can put in a README with some documentation and a link to the full file in the repository? 

Also, as a reminder to myself, we need to remember that the "master" conf will need to be read in in `get_config` but also anytime that it is retrieved from the ASDF file because it is inevitable that the conf will be updated between running `assemble` and subsequent subcommands.

**Comment by baagaard-usgs** [comment]
@emthompson-usgs Here are some thoughts on how we might reorganize the configuration.

## Short-term solution

* Create file(s) with the default values and have them installed to `$INSTALL/gmprocess/data/conf`.
* Look for a user config file and load the settings. Then load the default config files, but only load sections not already provided by the user.
* This would make the defaults clear; I don't think it would affect storing the provenance information.

### Complications

* Omitting sections in a user configuration file will be ambiguous; we have to be able to differentiate between a user wanting to use the default values and the user wanting to omit something. I suggest we add boolean flags to turn features on or off, where we currently rely on things being omitted to turn them off.
* A user would need to provide all parameters for any section with non-default values. This is not ideal and something we can fix in the long term, but this first step is arguably more user friendly than what we have now.

## Long-term solution

Develop a more sophisticated configuration so that users only need to specify specific values they want different from defaults rather than larger sections. This would require some reorganization of how we define parameters for each section, how to update small subsets, and how to differentiate between alternatives. I think this would require a more object oriented approach to the configuration.

**Comment by emthompson-usgs** [comment]
@baagaard-usgs, do you have any example projects that have something like what you are envisioning for the long term solution? I would consider doing something like this sooner so that we can avoid more iterations on how the config works, but I am having trouble understanding how it would work.

**Comment by baagaard-usgs** [comment]
@emthompson-usgs Unfortunately, I don't have any examples. I use something really simple for small projects (just update a dictionary) that can't handle these more complex configurations. For PyLith we use a sophisticated Python framework; it would require major reorganization of gmprocess and would probably be overkill.

In terms of implementation, storing the configuration using dataclasses or using [pydantic](https://pydantic-docs.helpmanual.io/usage/models/#recursive-models) might help.
