### ISSUE TITLE
cosmos writer error 

### ISSUE THREAD

**Issue by hadigh** [usgs/groundmotion-processing#913]
[cosmos_write_example.zip](https://github.com/usgs/groundmotion-processing/files/8656115/cosmos_write_example.zip)
Hi gmprocess team,

I am trying to write a cosmos file for processed streams in a .h5 file. I am using the 'CosmosWrite', and am getting the AttributeError:

**File ~/Tools/groundmotion-processing/gmprocess/io/cosmos/cosmos_writer.py:155, in Table4.get_matching_network(self, eventid)
    153 eventid = eventid.lower()
    154 for idx, row in self._dataframe.iterrows():
--> 155     network = row["IRIS Code"].lower()
    156     if eventid.startswith(network):
    157         return network

AttributeError: 'float' object has no attribute 'lower'**

Any help would be appreciated

**Comment by NNovoa-CDWR** [comment]
Hi,
I am looking into the discrepancy and will let you know when we resolve it.

Nicholas Novoa
COSMOS President

**Comment by emthompson-usgs** [comment]
Thanks @NNovoa-CDWR!

**Comment by hadigh** [comment]
@emthompson-usgs 

Thanks for looking into this, I can now successfully generate V2 files for my example, but getting the below error when setting the label to  label='unprocessed'

File ~/Tools/groundmotion-processing/gmprocess/io/cosmos/cosmos_writer.py:734, in CosmosWriter.write(self)
    732                 t2 = time.time()
    733                 t_write.append(t2 - t1)
--> 734 text_av = sum(t_text) / ntraces
    735 int_av = sum(t_int) / ntraces
    736 float_av = sum(t_float) / ntraces

ZeroDivisionError: division by zero

**Comment by emthompson-usgs** [comment]
Thanks for the report. I'll look into this.

**Comment by emthompson-usgs** [comment]
The underlying reason for this is that when @mhearne-usgs wrote this first version of the writer, he only included support for data that has been convert to physical units of acceleration (see [here](https://github.com/usgs/groundmotion-processing/blob/main/gmprocess/io/cosmos/cosmos_writer.py#L682-L688)). This is why none of the unprocessed records get included and this leads to a division by zero error. We can potentially add support for raw data with units of counts, or fix this so that it exits gracefully with a better error message but I'll need to consult @mhearne-usgs about this.

**Comment by emthompson-usgs** [comment]
@hadigh I just sent in a PR that will avoid the error and add a logging statement to indicate that no traces were processed in this case. 

The question I have for you is: How important is it for you to be able to write raw data with the COSMOS file? My (possibly incorrect) impression is that this format is mostly intended for people that are not able to directly make use of the ASDF format, which is exhaustive in terms of data/metadata. I expect that unprocessed/raw data may not be desired by these users. In fact, they won't have access to the instrument response without the ASDF file and so they wouldn't be able to convert to physical units for their analysis. 

Also, one suggestion for your script would be to add the logger so that logging messages get printed like this:
```
from gmprocess.utils.logging import setup_logger
setup_logger()
```

**Comment by hadigh** [comment]
@emthompson-usgs thanks for clarifying this and also the hint for logging. 

what you mentioned regarding the instrument response and user interest makes perfect sense,  what I am after is somehow between COSMOS V1 and V2: time-series in the physical unit only by applying basic baseline adjustment and instrument response correction and no additional filtering!

**Comment by emthompson-usgs** [comment]
Yeah, that seems reasonable. In fact the only sensible use of alternative labels that I can think of would be something like this, where you've processed the records using two different sets of processing parameters. We haven't had any call for that ourselves and so I don't know think that there's a simple way to automate this (e.g., use a different config file for different labels for a given project). For now, I'll close this issue. If you have ideas about changes to the code that would facilitate this, please create a new issue. 

Regarding the logger: that is what gets done when the `gmrecords` command starts. It would be nice if we had a way of having it setup automatically for scripts like this, but I don't know how to do that.
